# E-Commerce Sales & Customer Analytics

## 1. Project Overview

# E-Commerce Sales & Customer Analytics

## Business Problem

An e-commerce company wants to understand its sales performance, customer purchasing behavior, product profitability, and overall customer experience.

The company needs data-driven insights to identify high-value customers and products, understand the factors affecting sales and profitability, evaluate marketing and sales channels, and identify opportunities to improve customer retention and business performance.

## Project Objectives

- Analyze overall sales and profit performance.
- Understand customer purchasing behavior and customer segments.
- Identify high-performing and profitable products, categories, brands, and suppliers.
- Analyze customer experience through delivery, returns, ratings, and review sentiment.
- Evaluate marketing channels, campaigns, discounts, and loyalty activities.
- Provide actionable insights to support data-driven business decisions.

## 2. Import Libraries

Data Understanding & Profiling:
It helps us understand the dataset, its structure, values, and data-quality issues before cleaning and analysis.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 3. Load Dataset
Loads the e-commerce CSV dataset into a Pandas DataFrame.

In [23]:
df = pd.read_csv("ecommerce_sales_customer_analytics_150k.csv")

In [24]:
df

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

## 4. Initial Data Exploration

In [26]:
# View First 5 Rows
df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [27]:
# View Last 5 Rows
df.tail()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

In [28]:
# Check Dataset Shape
df.shape

(138116, 46)

In [29]:
# Check Column Names
# Displays all column names available in the dataset.
df.columns

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='object')

## 5. Data Quality Check

In [31]:
# Check Dataset Information
# Shows column data types, non-null counts, and memory information.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

In [32]:
# Check Columns with Missing Values
# Identifies how many missing values are present in each column.
df.isnull().sum()[df.isnull().sum() > 0]

delivery_days               24557
estimated_delivery_days     24557
return_status              128654
return_reason              128654
customer_rating             24557
review_sentiment            24557
customer_review             24557
campaign_name               83233
coupon_code                110502
dtype: int64

In [33]:
# Check Missing Value Percentage
# Calculates the percentage of missing values in each column.
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage[missing_percentage > 0].sort_values(ascending=False)

return_status              93.149237
return_reason              93.149237
coupon_code                80.006661
campaign_name              60.263112
delivery_days              17.779982
estimated_delivery_days    17.779982
customer_rating            17.779982
review_sentiment           17.779982
customer_review            17.779982
dtype: float64

In [34]:
# Check Duplicate Rows
# Checks whether completely duplicate records exist.
df.duplicated().sum()

0

## 6. Statistical Analysis
Provides statistical measures such as count, mean, median, minimum, and maximum for numerical columns.

In [36]:
df.describe()

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count
count,138116.000000,138116.000000,113559.000000,113559.000000,113559.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,45.862681,50210.889310,4.557772,4.298875,3.677015,103.991051,51.934128,5.615244,1375.384176,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,6.990559
std,16.467676,28569.767779,2.810012,2.594080,0.483672,115.175640,73.217692,3.371289,1291.009554,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,2.444166
min,18.000000,516.000000,0.000000,0.000000,1.600000,0.000000,0.000000,1.000000,6.310000,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,1.000000
25%,32.000000,25509.000000,2.000000,2.000000,3.400000,17.000000,3.000000,3.000000,458.920000,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,5.000000
50%,46.000000,50183.000000,4.000000,4.000000,3.700000,70.000000,25.000000,5.000000,995.730000,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,7.000000
75%,60.000000,74898.000000,7.000000,6.000000,4.000000,151.000000,71.000000,8.000000,1871.200000,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,9.000000
max,74.000000,99950.000000,14.000000,10.000000,5.000000,1621.000000,1063.000000,24.000000,16051.190000,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,20.000000

In [37]:
# Include All Columns
df.describe(include="all")

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
count,138116,138116,138116,138116,138116,138116,138116,138116.000000,138116,138116,...,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116,138116.000000
unique,138116,1826,68991,4,4,24911,21564,NaN,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,ORD-301242,2025-12-30,14:55:55,Completed,Mobile App,CUST-014687,John Smith,NaN,Female,Consumer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
freq,1,143,11,113559,55318,19,97,NaN,66439,75636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137782,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.862681,NaN,NaN,...,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,NaN,6.990559
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.467676,NaN,NaN,...,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,NaN,2.444166
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,...,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.000000,NaN,NaN,...,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,NaN,5.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.000000,NaN,NaN,...,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,NaN,7.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,NaN,NaN,...,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,NaN,9.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,NaN,...,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,NaN,20.000000

In [38]:
# Find Unique Values
# Shows the number of distinct values in each column.
df.nunique().sort_values()

return_status                    1
is_repeat_customer               2
customer_type                    3
review_sentiment                 3
gender                           3
customer_segment                 4
payment_status                   4
delivery_status                  4
shipping_method                  4
sales_channel                    4
order_status                     4
region                           5
currency                         7
customer_country                 7
payment_method                   7
return_reason                    8
marketing_channel               10
estimated_delivery_days         11
delivery_days                   15
campaign_name                   17
customer_order_count            19
warehouse                       19
quantity                        24
customer_review                 25
customer_rating                 35
customer_state                  38
coupon_code                     40
customer_age                    57
loyalty_points_redeemed        642
loyalty_points_earned          846
order_date                    1826
profit_margin_percentage      7947
shipping_cost                11973
customer_city                15516
customer_name                21564
customer_postal_code         22117
customer_lifetime_value      24752
customer_id                  24911
tax_amount                   43093
discount_amount              58437
order_time                   68991
product_cost                 88450
profit                       91021
gross_sales                 100130
net_sales                   112204
order_id                    138116
dtype: int64

## 7. Categorical Analysis

In [40]:
# First identify categorical columns
categorical_columns = df.select_dtypes(include="object").columns.tolist()

categorical_columns

['order_id',
 'order_date',
 'order_time',
 'order_status',
 'sales_channel',
 'customer_id',
 'customer_name',
 'gender',
 'customer_segment',
 'customer_type',
 'customer_city',
 'customer_state',
 'customer_country',
 'region',
 'payment_method',
 'payment_status',
 'currency',
 'shipping_method',
 'warehouse',
 'delivery_status',
 'return_status',
 'return_reason',
 'review_sentiment',
 'customer_review',
 'marketing_channel',
 'campaign_name',
 'coupon_code']

In [41]:
# Value Counts
df["gender"].value_counts()

gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

In [42]:
# Categorical Value Distribution
# Categorical Analysis – Value Counts (This code is used to see the different categories in each categorical column and count how many times each category appears.)
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- order_id ---
order_id
ORD-301242    1
ORD-749839    1
ORD-171306    1
ORD-107733    1
ORD-379479    1
             ..
ORD-696626    1
ORD-808841    1
ORD-208427    1
ORD-754385    1
ORD-528577    1
Name: count, Length: 138116, dtype: int64

--- order_date ---
order_date
2025-12-30    143
2022-12-06    137
2021-12-28    136
2022-12-12    135
2022-12-10    133
             ...
2022-02-06     42
2025-02-25     42
2021-02-01     42
2023-02-20     41
2021-02-17     37
Name: count, Length: 1826, dtype: int64

--- order_time ---
order_time
14:55:55    11
13:10:28    10
13:48:18     8
13:56:28     8
19:03:55     8
            ..
06:20:56     1
05:03:53     1
20:00:58     1
21:09:10     1
13:00:50     1
Name: count, Length: 68991, dtype: int64

--- order_status ---
order_status
Completed    113559
Returned       9462
Cancelled      8398
Pending        6697
Name: count, dtype: int64

--- sales_channel ---
sales_channel
Mobile App      55318
Website         48237
Marketplace     20698
Social Media    13863
Name: count, dtype: int64

--- customer_id ---
customer_id
CUST-014687    19
CUST-020091    17
CUST-012813    17
CUST-003453    17
CUST-020052    17
               ..
CUST-012868     1
CUST-007289     1
CUST-002533     1
CUST-014306     1
CUST-001647     1
Name: count, Length: 24911, dtype: int64

--- customer_name ---
customer_name
John Smith          97
Michael Smith       84
James Smith         67
Michael Johnson     65
John Brown          56
                    ..
Amy Owens            1
Jimmy Rose           1
Riley Matthews       1
Todd Ray             1
Deborah Saunders     1
Name: count, Length: 21564, dtype: int64

--- gender ---
gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

--- customer_segment ---
customer_segment
Consumer    75636
Premium     34746
VIP         13957
Business    13777
Name: count, dtype: int64

--- customer_type ---
customer_type
Loyal        129447
Returning      8335
New             334
Name: count, dtype: int64

--- customer_city ---
customer_city
Lake Michael            166
South Michael           163
South James             129
Port Michael            112
East Michael            105
                       ...
South Meganfurt           1
Annfort                   1
North Kristenborough      1
Watsonmouth               1
Mendozaport               1
Name: count, Length: 15516, dtype: int64

--- customer_state ---
customer_state
Pennsylvania         9148
California           8523
New York             8431
Georgia              8384
Michigan             8227
Ohio                 8207
Texas                8048
Illinois             8017
North Carolina       7874
Florida              7741
England              5213
Northern Ireland     5168
Scotland             4933
Wales                4921
North Rhine          2507
Baden-Württemberg    2344
Hesse                2310
Lower Saxony         2231
Bavaria              2201
British Columbia     1583
South Australia      1530
New South Wales      1457
Alberta              1452
Manitoba             1414
Western Australia    1412
Victoria             1353
Quebec               1287
Ontario              1279
Karnataka            1218
Uttar Pradesh        1209
Tamil Nadu           1121
Dubai                1104
Maharashtra          1097
Abu Dhabi            1072
Gujarat              1062
Queensland           1042
Sharjah              1041
Ajman                 955
Name: count, dtype: int64

--- customer_country ---
customer_country
USA          82600
UK           20235
Germany      11593
Canada        7015
Australia     6794
India         5707
UAE           4172
Name: count, dtype: int64

--- region ---
region
South      43990
Central    29627
West       26273
East       21602
North      16624
Name: count, dtype: int64

--- payment_method ---
payment_method
Credit Card          41460
Debit Card           27635
PayPal               20750
Digital Wallet       16382
Cash on Delivery     13863
Buy Now Pay Later    11061
Bank Transfer         6965
Name: count, dtype: int64

--- payment_status ---
payment_status
Paid        104250
Pending      13975
Failed       10429
Refunded      9462
Name: count, dtype: int64

--- currency ---
currency
USD    82600
GBP    20235
EUR    11593
CAD     7015
AUD     6794
INR     5707
AED     4172
Name: count, dtype: int64

--- shipping_method ---
shipping_method
Standard    62006
Express     34373
Economy     27824
Same Day    13913
Name: count, dtype: int64

--- warehouse ---
warehouse
WH-014    7447
WH-017    7389
WH-004    7384
WH-006    7345
WH-011    7314
WH-003    7305
WH-012    7305
WH-019    7298
WH-007    7294
WH-015    7294
WH-016    7271
WH-009    7239
WH-005    7236
WH-008    7206
WH-001    7199
WH-013    7174
WH-002    7154
WH-010    7139
WH-018    7123
Name: count, dtype: int64

--- delivery_status ---
delivery_status
On Time      86916
Cancelled    24557
Delayed      16886
Early         9757
Name: count, dtype: int64

--- return_status ---
return_status
Returned    9462
Name: count, dtype: int64

--- return_reason ---
return_reason
Wrong Product              1237
Other                      1208
Changed Mind               1204
Size Issue                 1182
Defective Product          1174
Late Delivery              1172
Product Not as Expected    1147
Damaged Product            1138
Name: count, dtype: int64

--- review_sentiment ---
review_sentiment
Positive    78083
Neutral     34684
Negative      792
Name: count, dtype: int64

--- customer_review ---
customer_review
Good value for money.                                       12237
Good product. Works as expected.                            12152
Met my expectations. Would recommend.                       12070
Satisfied with the purchase.                                11976
Product is okay, nothing special but works.                 11954
Decent quality for the price.                               11855
Quality could be improved.                                   6996
Product has some issues but it works.                        6973
Mixed feelings about this purchase.                          6929
Average product. Could be better.                            6898
Not what I expected but it's okay.                           6888
Product arrived quickly and works perfectly.                  744
Absolutely love this product! Exceeded all expectations.      742
Excellent customer service and amazing product.               738
Super satisfied with everything. Great value.                 737
Perfect product for my needs. Will buy again.                 736
Great quality and fast shipping. Highly recommend!            717
Best purchase I've made this year!                            717
Very happy with the quality and price.                        708
Waste of money. Very dissatisfied.                            146
Very disappointed with this product.                          139
Terrible experience. Will return.                             138
Product broke within a week.                                  134
Not worth the price at all.                                   129
Quality is poor. Not recommended.                             106
Name: count, dtype: int64

--- marketing_channel ---
marketing_channel
Organic Search     27742
Google Ads         20633
Direct             20515
Facebook Ads       16651
Instagram          13801
Email Marketing    11218
Referral           11191
Affiliate           6848
TikTok              5437
YouTube             4080
Name: count, dtype: int64

--- campaign_name ---
campaign_name
Default_Campaign      22989
Google_Search_Q1       2748
Google_Shopping        2746
Google_Display         2731
FB_Retargeting         2270
FB_Dynamic             2233
Friend_Invite          2232
Referral_Program       2198
FB_Prospecting         2161
Insta_Influencer       1822
Insta_Reels            1799
Insta_Stories          1773
Abandoned_Cart         1520
Weekly_Newsletter      1459
Promo_Email            1459
Influencer_Program     1404
Affiliate_Partner      1339
Name: count, dtype: int64

--- coupon_code ---
coupon_code
SAVE39    731
SAVE49    727
SAVE40    719
SAVE12    716
SAVE33    715
SAVE26    712
SAVE25    711
SAVE36    709
SAVE15    709
SAVE46    707
SAVE44    704
SAVE21    704
SAVE27    702
SAVE22    702
SAVE13    701
SAVE17    701
SAVE43    699
SAVE18    699
SAVE31    693
SAVE19    693
SAVE42    691
SAVE20    690
SAVE32    687
SAVE41    685
SAVE11    683
SAVE48    682
SAVE38    681
SAVE37    681
SAVE34    679
SAVE16    677
SAVE35    675
SAVE28    674
SAVE23    674
SAVE47    673
SAVE30    670
SAVE45    665
SAVE14    662
SAVE24    656
SAVE29    641
SAVE10    634
Name: count, dtype: int64

In [43]:
# Categorical Percentage Distribution
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print((df[col].value_counts(normalize=True) * 100).round(2))

--- order_id ---
order_id
ORD-301242    0.0
ORD-749839    0.0
ORD-171306    0.0
ORD-107733    0.0
ORD-379479    0.0
             ...
ORD-696626    0.0
ORD-808841    0.0
ORD-208427    0.0
ORD-754385    0.0
ORD-528577    0.0
Name: proportion, Length: 138116, dtype: float64

--- order_date ---
order_date
2025-12-30    0.10
2022-12-06    0.10
2021-12-28    0.10
2022-12-12    0.10
2022-12-10    0.10
              ...
2022-02-06    0.03
2025-02-25    0.03
2021-02-01    0.03
2023-02-20    0.03
2021-02-17    0.03
Name: proportion, Length: 1826, dtype: float64

--- order_time ---
order_time
14:55:55    0.01
13:10:28    0.01
13:48:18    0.01
13:56:28    0.01
19:03:55    0.01
            ...
06:20:56    0.00
05:03:53    0.00
20:00:58    0.00
21:09:10    0.00
13:00:50    0.00
Name: proportion, Length: 68991, dtype: float64

--- order_status ---
order_status
Completed    82.22
Returned      6.85
Cancelled     6.08
Pending       4.85
Name: proportion, dtype: float64

--- sales_channel ---
sales_channel
Mobile App      40.05
Website         34.92
Marketplace     14.99
Social Media    10.04
Name: proportion, dtype: float64

--- customer_id ---
customer_id
CUST-014687    0.01
CUST-020091    0.01
CUST-012813    0.01
CUST-003453    0.01
CUST-020052    0.01
               ...
CUST-012868    0.00
CUST-007289    0.00
CUST-002533    0.00
CUST-014306    0.00
CUST-001647    0.00
Name: proportion, Length: 24911, dtype: float64

--- customer_name ---
customer_name
John Smith          0.07
Michael Smith       0.06
James Smith         0.05
Michael Johnson     0.05
John Brown          0.04
                    ...
Amy Owens           0.00
Jimmy Rose          0.00
Riley Matthews      0.00
Todd Ray            0.00
Deborah Saunders    0.00
Name: proportion, Length: 21564, dtype: float64

--- gender ---
gender
Female        48.10
Male          47.99
Non-Binary     3.90
Name: proportion, dtype: float64

--- customer_segment ---
customer_segment
Consumer    54.76
Premium     25.16
VIP         10.11
Business     9.97
Name: proportion, dtype: float64

--- customer_type ---
customer_type
Loyal        93.72
Returning     6.03
New           0.24
Name: proportion, dtype: float64

--- customer_city ---
customer_city
Lake Michael            0.12
South Michael           0.12
South James             0.09
Port Michael            0.08
East Michael            0.08
                        ...
South Meganfurt         0.00
Annfort                 0.00
North Kristenborough    0.00
Watsonmouth             0.00
Mendozaport             0.00
Name: proportion, Length: 15516, dtype: float64

--- customer_state ---
customer_state
Pennsylvania         6.62
California           6.17
New York             6.10
Georgia              6.07
Michigan             5.96
Ohio                 5.94
Texas                5.83
Illinois             5.80
North Carolina       5.70
Florida              5.60
England              3.77
Northern Ireland     3.74
Scotland             3.57
Wales                3.56
North Rhine          1.82
Baden-Württemberg    1.70
Hesse                1.67
Lower Saxony         1.62
Bavaria              1.59
British Columbia     1.15
South Australia      1.11
New South Wales      1.05
Alberta              1.05
Manitoba             1.02
Western Australia    1.02
Victoria             0.98
Quebec               0.93
Ontario              0.93
Karnataka            0.88
Uttar Pradesh        0.88
Tamil Nadu           0.81
Dubai                0.80
Maharashtra          0.79
Abu Dhabi            0.78
Gujarat              0.77
Queensland           0.75
Sharjah              0.75
Ajman                0.69
Name: proportion, dtype: float64

--- customer_country ---
customer_country
USA          59.80
UK           14.65
Germany       8.39
Canada        5.08
Australia     4.92
India         4.13
UAE           3.02
Name: proportion, dtype: float64

--- region ---
region
South      31.85
Central    21.45
West       19.02
East       15.64
North      12.04
Name: proportion, dtype: float64

--- payment_method ---
payment_method
Credit Card          30.02
Debit Card           20.01
PayPal               15.02
Digital Wallet       11.86
Cash on Delivery     10.04
Buy Now Pay Later     8.01
Bank Transfer         5.04
Name: proportion, dtype: float64

--- payment_status ---
payment_status
Paid        75.48
Pending     10.12
Failed       7.55
Refunded     6.85
Name: proportion, dtype: float64

--- currency ---
currency
USD    59.80
GBP    14.65
EUR     8.39
CAD     5.08
AUD     4.92
INR     4.13
AED     3.02
Name: proportion, dtype: float64

--- shipping_method ---
shipping_method
Standard    44.89
Express     24.89
Economy     20.15
Same Day    10.07
Name: proportion, dtype: float64

--- warehouse ---
warehouse
WH-014    5.39
WH-017    5.35
WH-004    5.35
WH-006    5.32
WH-011    5.30
WH-003    5.29
WH-012    5.29
WH-019    5.28
WH-007    5.28
WH-015    5.28
WH-016    5.26
WH-009    5.24
WH-005    5.24
WH-008    5.22
WH-001    5.21
WH-013    5.19
WH-002    5.18
WH-010    5.17
WH-018    5.16
Name: proportion, dtype: float64

--- delivery_status ---
delivery_status
On Time      62.93
Cancelled    17.78
Delayed      12.23
Early         7.06
Name: proportion, dtype: float64

--- return_status ---
return_status
Returned    100.0
Name: proportion, dtype: float64

--- return_reason ---
return_reason
Wrong Product              13.07
Other                      12.77
Changed Mind               12.72
Size Issue                 12.49
Defective Product          12.41
Late Delivery              12.39
Product Not as Expected    12.12
Damaged Product            12.03
Name: proportion, dtype: float64

--- review_sentiment ---
review_sentiment
Positive    68.76
Neutral     30.54
Negative     0.70
Name: proportion, dtype: float64

--- customer_review ---
customer_review
Good value for money.                                       10.78
Good product. Works as expected.                            10.70
Met my expectations. Would recommend.                       10.63
Satisfied with the purchase.                                10.55
Product is okay, nothing special but works.                 10.53
Decent quality for the price.                               10.44
Quality could be improved.                                   6.16
Product has some issues but it works.                        6.14
Mixed feelings about this purchase.                          6.10
Average product. Could be better.                            6.07
Not what I expected but it's okay.                           6.07
Product arrived quickly and works perfectly.                 0.66
Absolutely love this product! Exceeded all expectations.     0.65
Excellent customer service and amazing product.              0.65
Super satisfied with everything. Great value.                0.65
Perfect product for my needs. Will buy again.                0.65
Great quality and fast shipping. Highly recommend!           0.63
Best purchase I've made this year!                           0.63
Very happy with the quality and price.                       0.62
Waste of money. Very dissatisfied.                           0.13
Very disappointed with this product.                         0.12
Terrible experience. Will return.                            0.12
Product broke within a week.                                 0.12
Not worth the price at all.                                  0.11
Quality is poor. Not recommended.                            0.09
Name: proportion, dtype: float64

--- marketing_channel ---
marketing_channel
Organic Search     20.09
Google Ads         14.94
Direct             14.85
Facebook Ads       12.06
Instagram           9.99
Email Marketing     8.12
Referral            8.10
Affiliate           4.96
TikTok              3.94
YouTube             2.95
Name: proportion, dtype: float64

--- campaign_name ---
campaign_name
Default_Campaign      41.89
Google_Search_Q1       5.01
Google_Shopping        5.00
Google_Display         4.98
FB_Retargeting         4.14
FB_Dynamic             4.07
Friend_Invite          4.07
Referral_Program       4.00
FB_Prospecting         3.94
Insta_Influencer       3.32
Insta_Reels            3.28
Insta_Stories          3.23
Abandoned_Cart         2.77
Weekly_Newsletter      2.66
Promo_Email            2.66
Influencer_Program     2.56
Affiliate_Partner      2.44
Name: proportion, dtype: float64

--- coupon_code ---
coupon_code
SAVE39    2.65
SAVE49    2.63
SAVE40    2.60
SAVE12    2.59
SAVE33    2.59
SAVE26    2.58
SAVE25    2.57
SAVE36    2.57
SAVE15    2.57
SAVE46    2.56
SAVE44    2.55
SAVE21    2.55
SAVE27    2.54
SAVE22    2.54
SAVE13    2.54
SAVE17    2.54
SAVE43    2.53
SAVE18    2.53
SAVE31    2.51
SAVE19    2.51
SAVE42    2.50
SAVE20    2.50
SAVE32    2.49
SAVE41    2.48
SAVE11    2.47
SAVE48    2.47
SAVE38    2.47
SAVE37    2.47
SAVE34    2.46
SAVE16    2.45
SAVE35    2.44
SAVE28    2.44
SAVE23    2.44
SAVE47    2.44
SAVE30    2.43
SAVE45    2.41
SAVE14    2.40
SAVE24    2.38
SAVE29    2.32
SAVE10    2.30
Name: proportion, dtype: float64

In [44]:
df["gender"].value_counts()

gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

## 8. Numerical Analysis

In [46]:
# Find Numerical Columns
# Identifies columns containing numerical data for numerical analysis.
numerical_columns = df.select_dtypes(include="number").columns.tolist()

numerical_columns

['customer_age',
 'customer_postal_code',
 'delivery_days',
 'estimated_delivery_days',
 'customer_rating',
 'loyalty_points_earned',
 'loyalty_points_redeemed',
 'quantity',
 'gross_sales',
 'discount_amount',
 'tax_amount',
 'shipping_cost',
 'net_sales',
 'product_cost',
 'profit',
 'profit_margin_percentage',
 'customer_lifetime_value',
 'customer_order_count']

In [47]:
# Basic numerical statistics
df[numerical_columns].describe()

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count
count,138116.000000,138116.000000,113559.000000,113559.000000,113559.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,45.862681,50210.889310,4.557772,4.298875,3.677015,103.991051,51.934128,5.615244,1375.384176,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,6.990559
std,16.467676,28569.767779,2.810012,2.594080,0.483672,115.175640,73.217692,3.371289,1291.009554,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,2.444166
min,18.000000,516.000000,0.000000,0.000000,1.600000,0.000000,0.000000,1.000000,6.310000,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,1.000000
25%,32.000000,25509.000000,2.000000,2.000000,3.400000,17.000000,3.000000,3.000000,458.920000,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,5.000000
50%,46.000000,50183.000000,4.000000,4.000000,3.700000,70.000000,25.000000,5.000000,995.730000,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,7.000000
75%,60.000000,74898.000000,7.000000,6.000000,4.000000,151.000000,71.000000,8.000000,1871.200000,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,9.000000
max,74.000000,99950.000000,14.000000,10.000000,5.000000,1621.000000,1063.000000,24.000000,16051.190000,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,20.000000

In [48]:
# Check the median
# Median tells us the middle value of the data. We check it because the median is less affected by very high or very low values than the mean.
df[numerical_columns].median()

customer_age                   46.000
customer_postal_code        50183.000
delivery_days                   4.000
estimated_delivery_days         4.000
customer_rating                 3.700
loyalty_points_earned          70.000
loyalty_points_redeemed        25.000
quantity                        5.000
gross_sales                   995.730
discount_amount               103.285
tax_amount                     77.010
shipping_cost                  19.190
net_sales                     950.760
product_cost                  478.955
profit                        408.395
profit_margin_percentage       46.990
customer_lifetime_value      8392.525
customer_order_count            7.000
dtype: float64

## 9. Data Cleaning
---> To identify and fix data-quality issues so the dataset is accurate and ready for analysis.

---> Missing values → Duplicates → Invalid values → Data types → Appropriate treatment

In [50]:
# Column Inventory
# it simply lists all the columns in our dataset.
# Before cleaning, we need to know what information our dataset contains.

for i, col in enumerate(df.columns, start=1):
    print(i, col)

1 order_id
2 order_date
3 order_time
4 order_status
5 sales_channel
6 customer_id
7 customer_name
8 customer_age
9 gender
10 customer_segment
11 customer_type
12 customer_city
13 customer_state
14 customer_country
15 region
16 customer_postal_code
17 payment_method
18 payment_status
19 currency
20 shipping_method
21 warehouse
22 delivery_days
23 estimated_delivery_days
24 delivery_status
25 return_status
26 return_reason
27 customer_rating
28 review_sentiment
29 customer_review
30 marketing_channel
31 campaign_name
32 coupon_code
33 loyalty_points_earned
34 loyalty_points_redeemed
35 quantity
36 gross_sales
37 discount_amount
38 tax_amount
39 shipping_cost
40 net_sales
41 product_cost
42 profit
43 profit_margin_percentage
44 customer_lifetime_value
45 is_repeat_customer
46 customer_order_count

In [51]:
# Check Missing Values
# It counts how many empty/missing values (NaN) are present in each column.

df.isnull().sum().sort_values(ascending=False)

return_reason               128654
return_status               128654
coupon_code                 110502
campaign_name                83233
estimated_delivery_days      24557
delivery_days                24557
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
loyalty_points_earned            0
loyalty_points_redeemed          0
order_id                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
quantity                         0
delivery_status                  0
order_date                       0
customer_type                    0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_city                    0
warehouse                        0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
customer_order_count             0
dtype: int64

In [52]:
# Investigate Columns with High Missing Values
# return_status
# return_reason
# coupon_code
# campaign_name
# delivery_days
# delivery status

In [53]:
# It counts each value in return_status, including missing values.
df["return_status"].value_counts(dropna=False)

return_status
NaN         128654
Returned      9462
Name: count, dtype: int64

In [54]:
# 9,462 rows have a return reason, and that exactly matches the 9,462 Returned orders we saw in return_status.
# No return was made / return reason is not applicable.
df["return_reason"].value_counts(dropna=False)

return_reason
NaN                        128654
Wrong Product                1237
Other                        1208
Changed Mind                 1204
Size Issue                   1182
Defective Product            1174
Late Delivery                1172
Product Not as Expected      1147
Damaged Product              1138
Name: count, dtype: int64

In [56]:
# It shows which coupon codes were used and how frequently they occurred, including missing values.
df["coupon_code"].value_counts(dropna=False)

coupon_code
NaN       110502
SAVE39       731
SAVE49       727
SAVE40       719
SAVE12       716
SAVE33       715
SAVE26       712
SAVE25       711
SAVE36       709
SAVE15       709
SAVE46       707
SAVE44       704
SAVE21       704
SAVE27       702
SAVE22       702
SAVE17       701
SAVE13       701
SAVE43       699
SAVE18       699
SAVE19       693
SAVE31       693
SAVE42       691
SAVE20       690
SAVE32       687
SAVE41       685
SAVE11       683
SAVE48       682
SAVE37       681
SAVE38       681
SAVE34       679
SAVE16       677
SAVE35       675
SAVE28       674
SAVE23       674
SAVE47       673
SAVE30       670
SAVE45       665
SAVE14       662
SAVE24       656
SAVE29       641
SAVE10       634
Name: count, dtype: int64

In [57]:
# It shows the different marketing campaigns associated with orders, including missing values.
df["campaign_name"].value_counts(dropna=False)

campaign_name
NaN                   83233
Default_Campaign      22989
Google_Search_Q1       2748
Google_Shopping        2746
Google_Display         2731
FB_Retargeting         2270
FB_Dynamic             2233
Friend_Invite          2232
Referral_Program       2198
FB_Prospecting         2161
Insta_Influencer       1822
Insta_Reels            1799
Insta_Stories          1773
Abandoned_Cart         1520
Weekly_Newsletter      1459
Promo_Email            1459
Influencer_Program     1404
Affiliate_Partner      1339
Name: count, dtype: int64

In [58]:
# It shows how many orders have each actual delivery time and how many are missing.
df["delivery_days"].value_counts(dropna=False).sort_index()

delivery_days
0.0      6674
1.0     13001
2.0      9244
3.0     17221
4.0     10763
5.0     13988
6.0     13434
7.0     13216
8.0      5207
9.0      4717
10.0     4245
11.0      997
12.0      428
13.0      282
14.0      142
NaN     24557
Name: count, dtype: int64

In [59]:
# It shows the number of orders in each delivery-status category.
df["delivery_status"].value_counts(dropna=False)

delivery_status
On Time      86916
Cancelled    24557
Delayed      16886
Early         9757
Name: count, dtype: int64

In [60]:
df["estimated_delivery_days"].value_counts(dropna=False).sort_index()

estimated_delivery_days
0.0      5794
1.0     15127
2.0      9380
3.0     19625
4.0     10247
5.0     14102
6.0     13871
7.0     13998
8.0      3855
9.0      3736
10.0     3824
NaN     24557
Name: count, dtype: int64

In [61]:
# It shows how customer ratings are distributed and how many ratings are missing.
#We found the missing ratings also matched the cancelled orders.
df["customer_rating"].value_counts(dropna=False).sort_index()

customer_rating
1.6        2
1.7        3
1.8        8
1.9       11
2.0       32
2.1       73
2.2      131
2.3      219
2.4      313
2.5      571
2.6      898
2.7     1288
2.8     1806
2.9     2527
3.0     3407
3.1     4476
3.2     5502
3.3     6618
3.4     7591
3.5     8755
3.6     9085
3.7     9362
3.8     9263
3.9     8744
4.0     7718
4.1     6628
4.2     5347
4.3     4177
4.4     3165
4.5     2197
4.6     1451
4.7      917
4.8      551
4.9      337
5.0      386
NaN    24557
Name: count, dtype: int64

In [63]:
df["review_sentiment"].value_counts(dropna=False)

review_sentiment
Positive    78083
Neutral     34684
NaN         24557
Negative      792
Name: count, dtype: int64

In [69]:
df.duplicated().sum()

0

In [73]:
# Fill missing values where NaN represents "not applicable"

df["return_status"] = df["return_status"].fillna("Not Returned")
df["return_reason"] = df["return_reason"].fillna("No Return")
df["coupon_code"] = df["coupon_code"].fillna("No Coupon")
df["campaign_name"] = df["campaign_name"].fillna("No Campaign")

In [74]:
df[[
    "return_status",
    "return_reason",
    "coupon_code",
    "campaign_name"
]].isnull().sum()

return_status    0
return_reason    0
coupon_code      0
campaign_name    0
dtype: int64

In [76]:
# Check for Invalid Values
print("Age below 18:", (df["customer_age"] < 18).sum())
print("Age above 100:", (df["customer_age"] > 100).sum())
print("Rating below 1:", (df["customer_rating"] < 1).sum())
print("Rating above 5:", (df["customer_rating"] > 5).sum())
print("Quantity <= 0:", (df["quantity"] <= 0).sum())
print("Negative gross sales:", (df["gross_sales"] < 0).sum())
print("Negative net sales:", (df["net_sales"] < 0).sum())

Age below 18: 0
Age above 100: 0
Rating below 1: 0
Rating above 5: 0
Quantity <= 0: 0
Negative gross sales: 0
Negative net sales: 0

In [78]:
# Data Type Check
df.dtypes

order_id                     object
order_date                   object
order_time                   object
order_status                 object
sales_channel                object
customer_id                  object
customer_name                object
customer_age                  int64
gender                       object
customer_segment             object
customer_type                object
customer_city                object
customer_state               object
customer_country             object
region                       object
customer_postal_code          int64
payment_method               object
payment_status               object
currency                     object
shipping_method              object
warehouse                    object
delivery_days               float64
estimated_delivery_days     float64
delivery_status              object
return_status                object
return_reason                object
customer_rating             float64
review_sentiment             object
customer_review              object
marketing_channel            object
campaign_name                object
coupon_code                  object
loyalty_points_earned         int64
loyalty_points_redeemed       int64
quantity                      int64
gross_sales                 float64
discount_amount             float64
tax_amount                  float64
shipping_cost               float64
net_sales                   float64
product_cost                float64
profit                      float64
profit_margin_percentage    float64
customer_lifetime_value     float64
is_repeat_customer             bool
customer_order_count          int64
dtype: object

In [79]:
# 1. Convert order_date to datetime
df["order_date"] = pd.to_datetime(df["order_date"])

# 2. Convert order_time to time
df["order_time"] = pd.to_datetime(df["order_time"], format="%H:%M:%S").dt.time

In [80]:
df[["order_date", "order_time"]].dtypes

order_date    datetime64[ns]
order_time            object
dtype: object

## 10. Feature Engineering

Creates new useful columns from existing data to make analysis easier and help answer business questions.

In [86]:
# Here we'll create a few useful new columns from the existing data, rather than creating lots of unnecessary features.

In [87]:
# 1.Create Order Month
# Extracts the year and month from order_date so we can analyze monthly sales and profit trends.

df["order_month"] = df["order_date"].dt.to_period("M").astype(str)

In [89]:
df[["order_date", "order_month"]].head()

  order_date order_month
0 2023-11-06     2023-11
1 2025-12-24     2025-12
2 2021-07-05     2021-07
3 2023-01-21     2023-01
4 2022-05-13     2022-05

In [90]:
# Create Delivery Delay
# delivery_days = actual delivery time
# estimated_delivery_days = expected delivery time
# Calculates the difference between actual and estimated delivery time.
# we can analyze delivery performance and customer satisfaction.

df["delivery_delay"] = (
    df["delivery_days"] - df["estimated_delivery_days"]
)

In [97]:
df[[
    "delivery_days",
    "estimated_delivery_days",
    "delivery_delay"
]].head()

   delivery_days  estimated_delivery_days  delivery_delay
0            3.0                      3.0             0.0
1           10.0                     10.0             0.0
2            3.0                      3.0             0.0
3            2.0                      2.0             0.0
4            6.0                      5.0             1.0

## 11. Outlier Detection

In [122]:
# Outlier Detection
financial_columns = [
    "gross_sales",
    "discount_amount",
    "net_sales",
    "product_cost",
    "profit",
    "customer_lifetime_value"
]

for col in financial_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    
    print(f"{col}: {outliers} outliers")

gross_sales: 6813 outliers
discount_amount: 12962 outliers
net_sales: 6435 outliers
product_cost: 7855 outliers
profit: 6514 outliers
customer_lifetime_value: 2075 outliers

# Outlier Decision
Outlier Treatment: The IQR method was used to identify potential outliers in key financial variables. The identified values were retained because they may represent genuine high-value transactions and customer activity rather than data errors.

## 12. Exploratory Data Analysis (EDA)

EDA means exploring the cleaned dataset to find patterns, trends, relationships, and useful business insights.

In [125]:
# 12.1 Monthly Sales and Profit Trend
# How do sales and profit change over time?
# How are the company's sales and profit performing month by month?

monthly_sales = (
    df.groupby("order_month")[["net_sales", "profit"]]
    .sum()
    .reset_index()
)

monthly_sales.head()

  order_month   net_sales      profit
0     2021-01  2374415.22  1129764.43
1     2021-02  1905413.15   900452.55
2     2021-03  2753256.18  1298951.77
3     2021-04  2469384.78  1178381.90
4     2021-05  2546555.37  1219361.44

In [127]:
# 12.2 — Sales by Customer Segment
# Groups the orders according to customer segment and calculates the total Net Sales generated by each segment.
# Which customer segments contribute the most to total sales?

segment_sales = (
    df.groupby("customer_segment")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

segment_sales

  customer_segment    net_sales
1         Consumer  97201007.90
2          Premium  44269794.13
3              VIP  17903164.81
0         Business  17760296.90

In [129]:
# 12.3 — Sales by Region
# Groups the orders by region and calculates the total Net Sales for each region.
# Which regions generate the highest and lowest total sales?

region_sales = (
    df.groupby("region")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

region_sales

    region    net_sales
3    South  55587994.98
0  Central  37171107.17
4     West  34755096.47
1     East  27054887.88
2    North  22565177.24

In [131]:
# 12.4 — Sales by Customer Type
# Groups the orders by customer type and calculates the total Net Sales for each type.
# Which customer type contributes the most to total sales?

customer_type_sales = (
    df.groupby("customer_type")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

customer_type_sales

  customer_type     net_sales
0         Loyal  1.661754e+08
2     Returning  1.052336e+07
1           New  4.354568e+05

In [133]:
# 12.5 — Sales by Gender
# Groups the orders by gender and calculates the total Net Sales for each gender.
# How is total sales distributed across genders?

gender_sales = (
    df.groupby("gender")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

gender_sales

       gender    net_sales
0      Female  85215914.19
1        Male  84900594.89
2  Non-Binary   7017754.66

In [135]:
# 12.6 — Sales by Payment Method
# Groups orders according to their payment method and calculates total Net Sales for each method.
# Which payment methods are associated with the highest total sales?

payment_sales = (
    df.groupby("payment_method")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

payment_sales

      payment_method    net_sales
3        Credit Card  53389617.40
4         Debit Card  35355144.13
6             PayPal  26632143.06
5     Digital Wallet  20832787.20
2   Cash on Delivery  18025912.13
1  Buy Now Pay Later  13974727.03
0      Bank Transfer   8923932.79

In [137]:
# 12.7 — Sales by Sales Channel
# Groups orders according to the sales channel and calculates total Net Sales for each channel.
# Which sales channel generates the most total sales?

channel_sales = (
    df.groupby("sales_channel")["net_sales"]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

channel_sales

  sales_channel    net_sales
1    Mobile App  70834782.53
3       Website  61854736.08
0   Marketplace  26696190.22
2  Social Media  17748554.91

In [139]:
# 12.8 — Profit by Customer Segment
# Groups orders by customer segment and calculates the total Profit generated by each segment.
# Which customer segment generates the most total profit?

segment_profit = (
    df.groupby("customer_segment")["profit"]
    .sum()
    .reset_index()
    .sort_values("profit", ascending=False)
)

segment_profit

  customer_segment       profit
1         Consumer  42819790.02
2          Premium  18177727.78
0         Business   7782525.28
3              VIP   7366352.68

In [141]:
# 12.9 — Profit by Region
# Compares total profit generated by each geographical region
# Which region generates the highest total profit?

region_profit = (
    df.groupby("region")["profit"]
    .sum()
    .reset_index()
    .sort_values("profit", ascending=False)
)

region_profit

    region       profit
3    South  23343946.17
4     West  15647252.47
0  Central  15572868.84
1     East  11179366.94
2    North  10402961.34

In [143]:
# 12.10 — Profit by Sales Channel
# Compares the total profit generated through each sales channel.
# Which sales channel generates the highest total profit?

channel_profit = (
    df.groupby("sales_channel")["profit"]
    .sum()
    .reset_index()
    .sort_values("profit", ascending=False)
)

channel_profit

  sales_channel       profit
1    Mobile App  30451112.22
3       Website  26639693.01
0   Marketplace  11414227.16
2  Social Media   7641363.37

In [145]:
# 12.11 — Repeat vs New Customer Performance
# Compares sales and profit from repeat customers versus non-repeat customers.
# Do repeat customers contribute more sales and profit?

repeat_customer_performance = (
    df.groupby("is_repeat_customer")[["net_sales", "profit"]]
    .sum()
    .reset_index()
)

repeat_customer_performance

   is_repeat_customer     net_sales       profit
0               False  4.354568e+05    192740.73
1                True  1.766988e+08  75953655.03

In [147]:
# 12.12 — Discount vs Sales & Profit
# Compares sales and profit for orders where a discount was applied versus orders without a discount.
# How do sales and profit differ between discounted and non-discounted orders?

df["discount_status"] = df["discount_amount"].apply(
    lambda x: "Discount Applied" if x > 0 else "No Discount"
)

discount_performance = (
    df.groupby("discount_status")[["net_sales", "profit"]]
    .sum()
    .reset_index()
)

discount_performance

    discount_status     net_sales       profit
0  Discount Applied  1.526047e+08  63246422.24
1       No Discount  2.452954e+07  12899973.52

In [149]:
# 12.13 — Delivery Status vs Sales & Profit
# Compares sales and profit across different delivery statuses.
# Which delivery status contributes the most sales and profit?

delivery_performance = (
    df.groupby("delivery_status")[["net_sales", "profit"]]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

delivery_performance

  delivery_status     net_sales       profit
3         On Time  1.102959e+08  45687906.29
0       Cancelled  3.293843e+07  16387926.73
1         Delayed  2.145506e+07   8876468.15
2           Early  1.244488e+07   5194094.59

In [151]:
# 12.14 — Marketing Channel Performance
# Compares sales and profit generated through different marketing channels.
# Which marketing channel generates the highest total sales and profit?

# Marketing Channel Performance

marketing_performance = (
    df.groupby("marketing_channel")[["net_sales", "profit"]]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

marketing_performance

  marketing_channel    net_sales       profit
6    Organic Search  35658209.46  15313174.30
4        Google Ads  26540586.44  11356389.55
1            Direct  26117885.52  11280316.74
3      Facebook Ads  21372470.11   9189184.91
5         Instagram  17676446.46   7585410.75
2   Email Marketing  14420446.43   6177791.79
7          Referral  14342124.81   6186481.45
0         Affiliate   8827899.78   3805557.93
8            TikTok   6980204.06   3011928.49
9           YouTube   5197990.67   2240159.85

In [153]:
# 12.15 — Return Analysis
# Examines returned vs non-returned orders and identifies the main reasons for returns.

# Return Status Analysis

return_analysis = (
    df.groupby("return_status")[["net_sales", "profit"]]
    .sum()
    .reset_index()
    .sort_values("net_sales", ascending=False)
)

return_analysis

  return_status     net_sales       profit
0  Not Returned  1.639616e+08  69220798.36
1      Returned  1.317267e+07   6925597.40

In [155]:
# Return Reason Analysis
# What are the most common reasons for product returns?

return_reason_analysis = (
    df[df["return_status"] == "Returned"]["return_reason"]
    .value_counts()
    .reset_index()
)

return_reason_analysis.columns = ["return_reason", "return_count"]

return_reason_analysis

             return_reason  return_count
0            Wrong Product          1237
1                    Other          1208
2             Changed Mind          1204
3               Size Issue          1182
4        Defective Product          1174
5            Late Delivery          1172
6  Product Not as Expected          1147
7          Damaged Product          1138

## 13. Export Cleaned Dataset

In [145]:
# 13.1 — Save Cleaned Dataset
df.to_csv("ecommerce_customer_behavior_cleaned.csv", index=False)

In [147]:
# 13.2 — Verify Exported File
import os

os.path.exists("ecommerce_customer_behavior_cleaned.csv")

True

In [149]:
# when we are not able to find the path of file
# find where the file was saved
import os

print(os.getcwd())

C:\Users\hp\Documents\Ecommerce_Sales_Customer_Analytics_Project

In [151]:
# Check the file exists there
import os

print(os.path.abspath("ecommerce_customer_behavior_cleaned.csv"))

C:\Users\hp\Documents\Ecommerce_Sales_Customer_Analytics_Project\ecommerce_customer_behavior_cleaned.csv

## Connecting Python script to MySQL

In [1]:
!pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\hp\anaconda3\lib\site-packages (26.7.0)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [157]:
from sqlalchemy import create_engine

# MySQL details
Username = "root"
Password = "@suhag123"
Database = "ecommerce_analytics"
table_name = "ecommerce_data"

# Create connection
engine = create_engine(
    "mysql+mysqlconnector://root:%40suhag123@localhost/ecommerce_analytics"
)

In [159]:
# Upload the dataset to MySQL
df.to_sql(
    "ecommerce_data",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

print("Data uploaded successfully!")

Data uploaded successfully!